spec:
  template:
    spec:
      containers:
      - name: addon-http-application-routing-nginx-ingress-controller
        ports:
         - containerPort: 9000
           hostPort: 9000
           protocol: TCP
           name: sonarqube
