spec:
  template:
    spec:
      containers:
      - name: addon-http-application-routing-nginx-ingress-controller
        ports:
         - containerPort: 1521
           hostPort: 1521
           protocol: TCP
           name: listener03
